### ISSUE TITLE
Cannot read properties of null (reading 'keyword')

### ISSUE THREAD

**Issue by mtrakal** [juanda99/arasaac-admin#57]
Steps:
- Open any pictogram, like: https://admin.arasaac.org/pictograms/2259
- Click on ➕
- Click into Word input field
- click anywhere outside / switch tab / ALT+TAB on Windows 10
- webapp crash on 

```
vendor.120fa183a88edee23286.chunk.js:1  TypeError: Cannot read properties of null (reading 'keyword')
    at main.ad589f81e477f4530740.chunk.js:1:1037396
    at n.componentDidUpdate (vendor.120fa183a88edee23286.chunk.js:1:2401603)
    at lc (vendor.120fa183a88edee23286.chunk.js:1:1578757)
    at vendor.120fa183a88edee23286.chunk.js:1:1596763
    at t.unstable_runWithPriority (vendor.120fa183a88edee23286.chunk.js:1:1352876)
    at Wa (vendor.120fa183a88edee23286.chunk.js:1:1540077)
    at xl (vendor.120fa183a88edee23286.chunk.js:1:1593253)
    at sl (vendor.120fa183a88edee23286.chunk.js:1:1589377)
    at vendor.120fa183a88edee23286.chunk.js:1:1540367
    at t.unstable_runWithPriority (vendor.120fa183a88edee23286.chunk.js:1:1352876)
rc @ vendor.120fa183a88edee23286.chunk.js:1
n.callback @ vendor.120fa183a88edee23286.chunk.js:1
ho @ vendor.120fa183a88edee23286.chunk.js:1
lc @ vendor.120fa183a88edee23286.chunk.js:1
(anonymous) @ vendor.120fa183a88edee23286.chunk.js:1
t.unstable_runWithPriority @ vendor.120fa183a88edee23286.chunk.js:1
Wa @ vendor.120fa183a88edee23286.chunk.js:1
xl @ vendor.120fa183a88edee23286.chunk.js:1
sl @ vendor.120fa183a88edee23286.chunk.js:1
(anonymous) @ vendor.120fa183a88edee23286.chunk.js:1
t.unstable_runWithPriority @ vendor.120fa183a88edee23286.chunk.js:1
Wa @ vendor.120fa183a88edee23286.chunk.js:1
Ga @ vendor.120fa183a88edee23286.chunk.js:1
qa @ vendor.120fa183a88edee23286.chunk.js:1
z @ vendor.120fa183a88edee23286.chunk.js:1
(anonymous) @ vendor.120fa183a88edee23286.chunk.js:1
vendor.120fa183a88edee23286.chunk.js:1  Uncaught TypeError: Cannot read properties of null (reading 'keyword')
    at main.ad589f81e477f4530740.chunk.js:1:1037396
    at n.componentDidUpdate (vendor.120fa183a88edee23286.chunk.js:1:2401603)
    at lc (vendor.120fa183a88edee23286.chunk.js:1:1578757)
    at vendor.120fa183a88edee23286.chunk.js:1:1596763
    at t.unstable_runWithPriority (vendor.120fa183a88edee23286.chunk.js:1:1352876)
    at Wa (vendor.120fa183a88edee23286.chunk.js:1:1540077)
    at xl (vendor.120fa183a88edee23286.chunk.js:1:1593253)
    at sl (vendor.120fa183a88edee23286.chunk.js:1:1589377)
    at vendor.120fa183a88edee23286.chunk.js:1:1540367
    at t.unstable_runWithPriority (vendor.120fa183a88edee23286.chunk.js:1:1352876)
```

https://github.com/juanda99/arasaac-admin/assets/1458891/032c8beb-b582-40bf-8687-c4bdd5f909f2

**Comment by juanda99** [comment]
Fixed!
